### ISSUE TITLE
GCC-ASAN warning on CRAN

### ISSUE THREAD

**Issue by helske** [helske/walker#13]
Got an email from CRAN, address sanitizer gives an error:

```
* using log directory ‘/data/gannet/ripley/R/packages/tests-gcc-SAN/walker.Rcheck’
* using R Under development (unstable) (2021-01-25 r79883)
* using platform: x86_64-pc-linux-gnu (64-bit)
* using session charset: UTF-8
* using option ‘--no-stop-on-test-error’
* checking for file ‘walker/DESCRIPTION’ ... OK
* checking extension type ... Package
* this is package ‘walker’ version ‘1.0.1’
* package encoding: UTF-8
* checking package dependencies ... OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking whether package ‘walker’ can be installed ... [61m/61m] WARNING
Found the following significant warnings:
  Warning: namespace ‘DBI’ is not available and has been replaced
See ‘/data/gannet/ripley/R/packages/tests-gcc-SAN/walker.Rcheck/00install.out’ for details.
* checking package directory ... OK
* checking whether the package can be loaded ... OK
* checking whether the package can be loaded with stated dependencies ... OK
* checking whether the package can be unloaded cleanly ... OK
* checking whether the namespace can be loaded with stated dependencies ... OK
* checking whether the namespace can be unloaded cleanly ... OK
* checking loading without being on the library search path ... OK
* checking compiled code ... OK
* checking installed files from ‘inst/doc’ ... OK
* checking files in ‘vignettes’ ... OK
* checking examples ... [87s/88s] OK
* checking tests ... [22s/22s] OK
  Running ‘test_all.R’ [21s/21s]
* checking package vignettes in ‘inst/doc’ ... OK
* checking re-building of vignette outputs ... [15m/15m] WARNING
Error(s) in re-building vignettes:
--- re-building ‘walker.Rmd’ using rmarkdown
=================================================================
==799014==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6020013a9e38 at pc 0x7f6889ef739a bp 0x7ffc79d59b00 sp 0x7ffc79d592a8
READ of size 4000 at 0x6020013a9e38 thread T0
    #0 0x7f6889ef7399 in memmove (/lib64/libasan.so.6+0x3a399)
    #1 0x7f685fc2bb46 in double* std::__copy_move<false, true, std::random_access_iterator_tag>::__copy_m<double>(double const*, double const*, double*) /usr/include/c++/10/bits/stl_algobase.h:426
    #2 0x7f685fc2bb46 in double* std::__copy_move_a2<false, double*, double*>(double*, double*, double*) /usr/include/c++/10/bits/stl_algobase.h:472
    #3 0x7f685fc2bb46 in double* std::__copy_move_a1<false, double*, double*>(double*, double*, double*) /usr/include/c++/10/bits/stl_algobase.h:506
    #4 0x7f685fc2bb46 in double* std::__copy_move_a<false, __gnu_cxx::__normal_iterator<double*, std::vector<double, std::allocator<double> > >, double*>(__gnu_cxx::__normal_iterator<double*, std::vector<double, std::allocator<double> > >, __gnu_cxx::__normal_iterator<double*, std::vector<double, std::allocator<double> > >, double*) /usr/include/c++/10/bits/stl_algobase.h:513
    #5 0x7f685fc2bb46 in double* std::copy<__gnu_cxx::__normal_iterator<double*, std::vector<double, std::allocator<double> > >, double*>(__gnu_cxx::__normal_iterator<double*, std::vector<double, std::allocator<double> > >, __gnu_cxx::__normal_iterator<double*, std::vector<double, std::allocator<double> > >, double*) /usr/include/c++/10/bits/stl_algobase.h:569
    #6 0x7f685fc2bb46 in void std::vector<double, std::allocator<double> >::_M_assign_aux<__gnu_cxx::__normal_iterator<double*, std::vector<double, std::allocator<double> > > >(__gnu_cxx::__normal_iterator<double*, std::vector<double, std::allocator<double> > >, __gnu_cxx::__normal_iterator<double*, std::vector<double, std::allocator<double> > >, std::forward_iterator_tag) /usr/include/c++/10/bits/vector.tcc:321
    #7 0x7f685fc2ed5c in void std::vector<double, std::allocator<double> >::_M_assign_dispatch<__gnu_cxx::__normal_iterator<double*, std::vector<double, std::allocator<double> > > >(__gnu_cxx::__normal_iterator<double*, std::vector<double, std::allocator<double> > >, __gnu_cxx::__normal_iterator<double*, std::vector<double, std::allocator<double> > >, std::__false_type) /usr/include/c++/10/bits/stl_vector.h:1628
    #8 0x7f685fc2ed5c in void std::vector<double, std::allocator<double> >::assign<__gnu_cxx::__normal_iterator<double*, std::vector<double, std::allocator<double> > >, void>(__gnu_cxx::__normal_iterator<double*, std::vector<double, std::allocator<double> > >, __gnu_cxx::__normal_iterator<double*, std::vector<double, std::allocator<double> > >) /usr/include/c++/10/bits/stl_vector.h:769
    #9 0x7f685fc2ed5c in split_potential_scale_reduction /tmp/Rtmp5Oq3an/R.INSTALL327d7a20b63ed9/rstan/src/chains.cpp:568
    #10 0x57d4a7 in R_doDotCall /data/gannet/ripley/R/svn/R-devel/src/main/dotcode.c:601
    #11 0x639251 in bcEval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:7671
    #12 0x670607 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:727
    #13 0x6758f4 in R_execClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1897
    #14 0x677d97 in Rf_applyClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1823
    #15 0x64704e in bcEval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:7083
    #16 0x670607 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:727
    #17 0x6758f4 in R_execClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1897
    #18 0x677d97 in Rf_applyClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1823
    #19 0x67decd in R_forceAndCall /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1964
    #20 0x44c88a in do_lapply /data/gannet/ripley/R/svn/R-devel/src/main/apply.c:70
    #21 0x71bba9 in do_internal /data/gannet/ripley/R/svn/R-devel/src/main/names.c:1397
    #22 0x623b9c in bcEval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:7135
    #23 0x670607 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:727
    #24 0x6758f4 in R_execClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1897
    #25 0x677d97 in Rf_applyClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1823
    #26 0x64704e in bcEval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:7083
    #27 0x670607 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:727
    #28 0x6758f4 in R_execClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1897
    #29 0x677d97 in Rf_applyClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1823
    #30 0x64704e in bcEval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:7083
    #31 0x670607 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:727
    #32 0x672652 in forcePromise /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:555
    #33 0x672de7 in FORCE_PROMISE /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:5136
    #34 0x672de7 in getvar /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:5177
    #35 0x63727a in bcEval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:6867
    #36 0x670607 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:727
    #37 0x6758f4 in R_execClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1897
    #38 0x677d97 in Rf_applyClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1823
    #39 0x64704e in bcEval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:7083
    #40 0x670607 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:727
    #41 0x6758f4 in R_execClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1897
    #42 0x677d97 in Rf_applyClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1823
    #43 0x64704e in bcEval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:7083
    #44 0x670607 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:727
    #45 0x672652 in forcePromise /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:555
    #46 0x672de7 in FORCE_PROMISE /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:5136
    #47 0x672de7 in getvar /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:5177
    #48 0x63727a in bcEval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:6867
    #49 0x670607 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:727
    #50 0x6758f4 in R_execClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1897
    #51 0x677d97 in Rf_applyClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1823
    #52 0x64704e in bcEval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:7083
    #53 0x670607 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:727
    #54 0x6758f4 in R_execClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1897
    #55 0x677d97 in Rf_applyClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1823
    #56 0x64704e in bcEval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:7083
    #57 0x670607 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:727
    #58 0x6758f4 in R_execClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1897
    #59 0x6786e6 in R_execMethod /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:2073
    #60 0x7f687d1b8429 in R_dispatchGeneric /data/gannet/ripley/R/svn/R-devel/src/library/methods/src/methods_list_dispatch.c:1140
    #61 0x728310 in do_standardGeneric /data/gannet/ripley/R/svn/R-devel/src/main/objects.c:1285
    #62 0x6716ba in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:834
    #63 0x6758f4 in R_execClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1897
    #64 0x677d97 in Rf_applyClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1823
    #65 0x64704e in bcEval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:7083
    #66 0x670607 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:727
    #67 0x6758f4 in R_execClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1897
    #68 0x677d97 in Rf_applyClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1823
    #69 0x72155e in dispatchMethod /data/gannet/ripley/R/svn/R-devel/src/main/objects.c:436
    #70 0x72205f in Rf_usemethod /data/gannet/ripley/R/svn/R-devel/src/main/objects.c:476
    #71 0x722b93 in do_usemethod /data/gannet/ripley/R/svn/R-devel/src/main/objects.c:565
    #72 0x623b9c in bcEval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:7135
    #73 0x670607 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:727
    #74 0x6758f4 in R_execClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1897
    #75 0x677d97 in Rf_applyClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1823
    #76 0x670ecf in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:850
    #77 0x67fe27 in do_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:3344
    #78 0x6288eb in bcEval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:7115
    #79 0x670607 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:727
    #80 0x6758f4 in R_execClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1897
    #81 0x677d97 in Rf_applyClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1823
    #82 0x64704e in bcEval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:7083
    #83 0x670607 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:727
    #84 0x672652 in forcePromise /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:555
    #85 0x670c13 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:750
    #86 0x68167c in do_withVisible /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:3396
    #87 0x71bba9 in do_internal /data/gannet/ripley/R/svn/R-devel/src/main/names.c:1397
    #88 0x623b9c in bcEval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:7135
    #89 0x670607 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:727
    #90 0x6758f4 in R_execClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1897
    #91 0x677d97 in Rf_applyClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1823
    #92 0x64704e in bcEval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:7083
    #93 0x670607 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:727
    #94 0x672652 in forcePromise /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:555
    #95 0x672de7 in FORCE_PROMISE /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:5136
    #96 0x672de7 in getvar /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:5177
    #97 0x63727a in bcEval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:6867
    #98 0x670607 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:727
    #99 0x6758f4 in R_execClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1897
    #100 0x677d97 in Rf_applyClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1823
    #101 0x64704e in bcEval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:7083
    #102 0x670607 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:727
    #103 0x672652 in forcePromise /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:555
    #104 0x672de7 in FORCE_PROMISE /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:5136
    #105 0x672de7 in getvar /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:5177
    #106 0x63727a in bcEval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:6867
    #107 0x670607 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:727
    #108 0x6758f4 in R_execClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1897
    #109 0x677d97 in Rf_applyClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1823
    #110 0x64704e in bcEval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:7083
    #111 0x670607 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:727
    #112 0x672652 in forcePromise /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:555
    #113 0x672de7 in FORCE_PROMISE /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:5136
    #114 0x672de7 in getvar /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:5177
    #115 0x63727a in bcEval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:6867
    #116 0x670607 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:727
    #117 0x6758f4 in R_execClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1897
    #118 0x677d97 in Rf_applyClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1823
    #119 0x64704e in bcEval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:7083
    #120 0x670607 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:727
    #121 0x6758f4 in R_execClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1897
    #122 0x677d97 in Rf_applyClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1823
    #123 0x64704e in bcEval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:7083
    #124 0x670607 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:727
    #125 0x6758f4 in R_execClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1897
    #126 0x677d97 in Rf_applyClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1823
    #127 0x670ecf in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:850
    #128 0x6758f4 in R_execClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1897
    #129 0x677d97 in Rf_applyClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1823
    #130 0x64704e in bcEval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:7083
    #131 0x670607 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:727
    #132 0x672652 in forcePromise /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:555
    #133 0x672de7 in FORCE_PROMISE /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:5136
    #134 0x672de7 in getvar /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:5177
    #135 0x63727a in bcEval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:6867
    #136 0x670607 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:727
    #137 0x6758f4 in R_execClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1897
    #138 0x677d97 in Rf_applyClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1823
    #139 0x64704e in bcEval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:7083
    #140 0x670607 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:727
    #141 0x6758f4 in R_execClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1897
    #142 0x677d97 in Rf_applyClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1823
    #143 0x64704e in bcEval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:7083
    #144 0x670607 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:727
    #145 0x6758f4 in R_execClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1897
    #146 0x677d97 in Rf_applyClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1823
    #147 0x64704e in bcEval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:7083
    #148 0x670607 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:727
    #149 0x6758f4 in R_execClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1897
    #150 0x677d97 in Rf_applyClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1823
    #151 0x72155e in dispatchMethod /data/gannet/ripley/R/svn/R-devel/src/main/objects.c:436
    #152 0x72205f in Rf_usemethod /data/gannet/ripley/R/svn/R-devel/src/main/objects.c:476
    #153 0x722b93 in do_usemethod /data/gannet/ripley/R/svn/R-devel/src/main/objects.c:565
    #154 0x623b9c in bcEval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:7135
    #155 0x670607 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:727
    #156 0x6758f4 in R_execClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1897
    #157 0x677d97 in Rf_applyClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1823
    #158 0x64704e in bcEval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:7083
    #159 0x670607 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:727
    #160 0x672652 in forcePromise /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:555
    #161 0x672de7 in FORCE_PROMISE /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:5136
    #162 0x672de7 in getvar /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:5177
    #163 0x63727a in bcEval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:6867
    #164 0x670607 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:727
    #165 0x6758f4 in R_execClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1897
    #166 0x677d97 in Rf_applyClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1823
    #167 0x64704e in bcEval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:7083
    #168 0x670607 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:727
    #169 0x6758f4 in R_execClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1897
    #170 0x677d97 in Rf_applyClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1823
    #171 0x64704e in bcEval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:7083
    #172 0x670607 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:727
    #173 0x6758f4 in R_execClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1897
    #174 0x677d97 in Rf_applyClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1823
    #175 0x64704e in bcEval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:7083
    #176 0x670607 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:727
    #177 0x6758f4 in R_execClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1897
    #178 0x677d97 in Rf_applyClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1823
    #179 0x64704e in bcEval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:7083
    #180 0x670607 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:727
    #181 0x6758f4 in R_execClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1897
    #182 0x677d97 in Rf_applyClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1823
    #183 0x64704e in bcEval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:7083
    #184 0x670607 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:727
    #185 0x6758f4 in R_execClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1897
    #186 0x677d97 in Rf_applyClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1823
    #187 0x64704e in bcEval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:7083
    #188 0x670607 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:727
    #189 0x672652 in forcePromise /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:555
    #190 0x672de7 in FORCE_PROMISE /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:5136
    #191 0x672de7 in getvar /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:5177
    #192 0x63727a in bcEval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:6867
    #193 0x670607 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:727
    #194 0x672652 in forcePromise /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:555
    #195 0x672de7 in FORCE_PROMISE /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:5136
    #196 0x672de7 in getvar /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:5177
    #197 0x63727a in bcEval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:6867
    #198 0x670607 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:727
    #199 0x672652 in forcePromise /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:555
    #200 0x672de7 in FORCE_PROMISE /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:5136
    #201 0x672de7 in getvar /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:5177
    #202 0x63727a in bcEval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:6867
    #203 0x670607 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:727
    #204 0x672652 in forcePromise /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:555
    #205 0x672de7 in FORCE_PROMISE /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:5136
    #206 0x672de7 in getvar /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:5177
    #207 0x63727a in bcEval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:6867
    #208 0x670607 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:727
    #209 0x6758f4 in R_execClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1897
    #210 0x677d97 in Rf_applyClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1823
    #211 0x64704e in bcEval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:7083
    #212 0x670607 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:727
    #213 0x6758f4 in R_execClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1897
    #214 0x677d97 in Rf_applyClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1823
    #215 0x64704e in bcEval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:7083
    #216 0x670607 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:727
    #217 0x6758f4 in R_execClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1897
    #218 0x677d97 in Rf_applyClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1823
    #219 0x64704e in bcEval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:7083
    #220 0x670607 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:727
    #221 0x6758f4 in R_execClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1897
    #222 0x677d97 in Rf_applyClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1823
    #223 0x64704e in bcEval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:7083
    #224 0x670607 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:727
    #225 0x6758f4 in R_execClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1897
    #226 0x677d97 in Rf_applyClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1823
    #227 0x670ecf in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:850
    #228 0x6f0c0d in Rf_ReplIteration /data/gannet/ripley/R/svn/R-devel/src/main/main.c:264
    #229 0x6f1258 in R_ReplConsole /data/gannet/ripley/R/svn/R-devel/src/main/main.c:314
    #230 0x6f13a4 in run_Rmainloop /data/gannet/ripley/R/svn/R-devel/src/main/main.c:1113
    #231 0x6f13f2 in Rf_mainloop /data/gannet/ripley/R/svn/R-devel/src/main/main.c:1120
    #232 0x41b3c8 in main /data/gannet/ripley/R/svn/R-devel/src/main/Rmain.c:29
    #233 0x7f6888877081 in __libc_start_main (/lib64/libc.so.6+0x27081)
    #234 0x41db3d in _start (/data/gannet/ripley/R/gcc-SAN/bin/exec/R+0x41db3d)

0x6020013a9e38 is located 0 bytes to the right of 8-byte region [0x6020013a9e30,0x6020013a9e38)
allocated by thread T0 here:
    #0 0x7f6889f6f067 in operator new(unsigned long) (/lib64/libasan.so.6+0xb2067)
    #1 0x7f685fc2b97f in __gnu_cxx::new_allocator<double>::allocate(unsigned long, void const*) /usr/include/c++/10/ext/new_allocator.h:115
    #2 0x7f685fc2b97f in std::allocator_traits<std::allocator<double> >::allocate(std::allocator<double>&, unsigned long) /usr/include/c++/10/bits/alloc_traits.h:460
    #3 0x7f685fc2b97f in std::_Vector_base<double, std::allocator<double> >::_M_allocate(unsigned long) /usr/include/c++/10/bits/stl_vector.h:346
    #4 0x7f685fc2b97f in double* std::vector<double, std::allocator<double> >::_M_allocate_and_copy<double*>(unsigned long, double*, double*) /usr/include/c++/10/bits/stl_vector.h:1511
    #5 0x7f685fc2b97f in void std::vector<double, std::allocator<double> >::_M_assign_aux<double*>(double*, double*, std::forward_iterator_tag) /usr/include/c++/10/bits/vector.tcc:309

SUMMARY: AddressSanitizer: heap-buffer-overflow (/lib64/libasan.so.6+0x3a399) in memmove
Shadow bytes around the buggy address:
  0x0c048026d370: fa fa fd fd fa fa fd fa fa fa fd fa fa fa fd fa
  0x0c048026d380: fa fa fd fd fa fa fd fa fa fa fd fa fa fa fd fd
  0x0c048026d390: fa fa fd fd fa fa fd fd fa fa 01 fa fa fa 01 fa
  0x0c048026d3a0: fa fa 01 fa fa fa 01 fa fa fa 01 fa fa fa 01 fa
  0x0c048026d3b0: fa fa fa fa fa fa fd fa fa fa fd fd fa fa fd fa
=>0x0c048026d3c0: fa fa fd fa fa fa 00[fa]fa fa 04 fa fa fa 04 fa
  0x0c048026d3d0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c048026d3e0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fd fd
  0x0c048026d3f0: fa fa 04 fa fa fa fd fd fa fa fd fa fa fa fd fa
  0x0c048026d400: fa fa fa fa fa fa 01 fa fa fa 01 fa fa fa 01 fa
  0x0c048026d410: fa fa 01 fa fa fa 01 fa fa fa 01 fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==799014==ABORTING

* DONE
Status: 2 WARNINGs
```
Seems to be related to `rstan` (no surprise as almost all the compiled code is generated by Stan). For some reason the sanitizer check on rhub does not work at the moment, so not sure if it is just an issue on CRAN side.

**Comment by helske** [comment]
Actually maybe this is due to me tweaking the stanfit object in order to save space.

**Comment by helske** [comment]
Should be fixed now.
